spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/faqtech
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always